name: prod docker ci (storybook)

on:
  push:
    tags:
      - v*

permissions:
  packages: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to Github Packages Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:run-${{ github.run_id }}-${{ github.run_attempt }}
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
